name: Bucket Minion
description: Set of actions to automate Shovel bucket maintaining.
author: Jakub <Ash258> Čábera
# TODO: Wait for proper powershell support
runs:
    using: node12
    main: _init/index.js
branding:
    icon: package
    color: purple
